package com.example.app30dias.ui.theme

import androidx.compose.ui.graphics.Color

// Paleta clara (tema claro)
val light_primary = Color(0xFF9A4324)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFFDBCC)
val light_onPrimaryContainer = Color(0xFF360D00)
val light_secondary = Color(0xFF77574A)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFFFDBCE)
val light_onSecondaryContainer = Color(0xFF2C160C)
val light_tertiary = Color(0xFF606235)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFE5E7AE)
val light_onTertiaryContainer = Color(0xFF1C1E00)
val light_error = Color(0xFFBA1A1A)
val light_onError = Color(0xFFFFFFFF)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFF8F5)
val light_onBackground = Color(0xFF221A16)
val light_surface = Color(0xFFFFF8F5)
val light_onSurface = Color(0xFF221A16)
val light_surfaceVariant = Color(0xFFF4DED5)
val light_onSurfaceVariant = Color(0xFF53433D)
val light_outline = Color(0xFF85736C)
val light_outlineVariant = Color(0xFFD8C2B9)

// Paleta oscura (tema oscuro)
val dark_primary = Color(0xFFFFB595)
val dark_onPrimary = Color(0xFF561F05)
val dark_primaryContainer = Color(0xFF7A320F)
val dark_onPrimaryContainer = Color(0xFFFFDBCC)
val dark_secondary = Color(0xFFE7BDAE)
val dark_onSecondary = Color(0xFF442A1F)
val dark_secondaryContainer = Color(0xFF5D4034)
val dark_onSecondaryContainer = Color(0xFFFFDBCE)
val dark_tertiary = Color(0xFFC9CB95)
val dark_onTertiary = Color(0xFF31330A)
val dark_tertiaryContainer = Color(0xFF48491F)
val dark_onTertiaryContainer = Color(0xFFE5E7AE)
val dark_error = Color(0xFFFFB4AB)
val dark_onError = Color(0xFF690005)
val dark_errorContainer = Color(0xFF93000A)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1A120E)
val dark_onBackground = Color(0xFFF0DFD8)
val dark_surface = Color(0xFF1A120E)
val dark_onSurface = Color(0xFFF0DFD8)
val dark_surfaceVariant = Color(0xFF53433D)
val dark_onSurfaceVariant = Color(0xFFD7C2B9)
val dark_outline = Color(0xFFA08D84)
val dark_outlineVariant = Color(0xFF53433D)